version: 2
updates:
  # Python dependencies updates
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"  # No direct 6-month option, but we can manually delay updates
      day: "1"  # Runs on the 1st of every month
      time: "00:00"  # Midnight UTC
    ignore:
      - dependency-name: "selenium"
        versions: ["<4.0.0"]

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"  # Also set to monthly, but we can skip PRs if not needed
      day: "1"
      time: "00:00"
    ignore:
      - dependency-name: "actions/checkout"
        versions: ["<3.0.0"]
