version: 2
updates:

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "00:00"
    ignore:
      - dependency-name: "selenium"
        versions: ["<4.10.0"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "00:00"
    ignore:
      - dependency-name: "actions/checkout"
        versions: ["<3.0.0"]
        