version: 2
updates:
  # Python dependencies updates
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"  # Runs once a month
      day: "monday"  # Runs on the first Monday of the month
      time: "00:00"  # Midnight UTC
    ignore:
      - dependency-name: "selenium"
        versions: ["<4.0.0"]

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"  # Runs once a month
      day: "monday"  # First Monday of the month
      time: "00:00"
    ignore:
      - dependency-name: "actions/checkout"
        versions: ["<3.0.0"]
