version: 2
updates:
  # Python dependencies updates
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "time"
      time: "2024-07-01T00:00:00Z" # First run on July 1, 2024
    ignore:
      - dependency-name: "selenium"
        versions: ["<4.0.0"]

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "time"
      time: "2025-01-01T00:00:00Z" # Next run on Jan 1, 2025
    ignore:
      - dependency-name: "actions/checkout"
        versions: ["<3.0.0"]
