version: 2
updates:
  # Python dependencies updates
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"             # Check for updates weekly (can be "daily", "weekly", or "monthly")
      day: "sunday"                  # Specify the day updates are checked
    ignore:
      - dependency-name: "selenium"  # Ignore specific package updates
        versions: ["<4.0.0"]         # Ignore versions below specified
  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"                   # Check for updates in the root directory
    schedule:
      interval: "weekly"             # Check for updates weekly
      day: "monday"                  # Day updates are checked (optional)
    ignore:
      - dependency-name: "actions/checkout"  # Ignore specific Actions updates
        versions: ["<3.0.0"]                 # Ignore versions below specified
