# Bandit Security Scan Workflow
# Scans the codebase for security vulnerabilities using Bandit.

name: Bandit Security Scan

on:
  push:
    branches: [ "main" ]  # Trigger on pushes to the main branch
  pull_request:
    branches: [ "main" ]  # Trigger on pull requests targeting the main branch
  schedule:
    - cron: '34 8 * * 1'  # Run every Monday at 08:34 UTC

permissions:
  contents: read            # Allows fetching repository code
  security-events: write    # Enables uploading SARIF results to GitHub Security tab

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Match your project's Python version

      # Step 3: Install Bandit
      - name: Install Bandit
        run: python -m pip install --upgrade bandit bandit-sarif

      # Step 4: Run Bandit Security Scan
      - name: Run Bandit Security Scan
        run: |
          bandit -r . -f json -o bandit-results.json \
                 --skip B101,B404,B605 \
                 --exclude __pycache__,*.pyc,logs,dist,build,migrations \
                 --exit-zero
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Convert JSON to SARIF Format
      - name: Convert JSON to SARIF
        run: bandit-sarif -i bandit-results.json -o bandit-results.sarif

      # Step 6: Upload SARIF Results to GitHub Security Tab
      - name: Upload SARIF Results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: bandit-results.sarif
