name: Page Update Download Links

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - pyproject.toml

permissions:
  contents: write

jobs:
  update-download-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Get version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(python3 -c "import re; f=open('pyproject.toml').read(); print(re.search(r'version\s*=\s*[\"\\'](.+?)[\"\\']', f).group(1))")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update download links in HTML
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          sed -i "s|https://github.com/nayandas69/auto-website-visitor/releases/download/.*/awv.exe|https://github.com/nayandas69/auto-website-visitor/releases/download/${VERSION}/awv.exe|g" index.html
          sed -i "s|https://github.com/nayandas69/auto-website-visitor/releases/download/.*/awv-linux.tar.gz|https://github.com/nayandas69/auto-website-visitor/releases/download/${VERSION}/awv-linux.tar.gz|g" index.html
          sed -i "s|https://github.com/nayandas69/auto-website-visitor/releases/download/.*/auto-website-visitor_.*_amd64.deb|https://github.com/nayandas69/auto-website-visitor/releases/download/${VERSION}/auto-website-visitor_${VERSION}_amd64.deb|g" index.html

      - name: Commit and push changes to dev
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Update download links to version ${{ steps.get_version.outputs.version }}" || echo "No changes to commit"
          git push origin dev
