name: Python Package CI and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel twine requests

      - name: Clean build artifacts
        run: |
          rm -rf dist/ build/ *.egg-info

      - name: Build the package
        run: |
          python setup.py sdist bdist_wheel

      - name: Check if version exists on PyPI
        id: check-version
        env:
          PACKAGE_NAME: "auto-website-visitor"
        run: |
          VERSION=$(python setup.py --version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://pypi.org/project/$PACKAGE_NAME/$VERSION/)
          if [ "$RESPONSE" -eq 200 ]; then
            echo "Version $VERSION already exists on PyPI."
            echo "UPLOAD_REQUIRED=false" >> $GITHUB_ENV
          else
            echo "Version $VERSION does not exist on PyPI."
            echo "UPLOAD_REQUIRED=true" >> $GITHUB_ENV

      - name: Publish to PyPI
        if: env.UPLOAD_REQUIRED == 'true'
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m twine upload dist/*
