name: Release Tags

on:
  workflow_dispatch:
  push:
    paths:
      - 'awv/awv.py'
    branches:
      - main

permissions:
  contents: write

jobs:
  linux-build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Extract version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(python -c "import re; f=open('pyproject.toml').read(); print(re.search(r'version\s*=\s*[\"\\'](.+?)[\"\\']', f).group(1))")
          echo "Project version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if Git tag exists
        id: tag_check
        run: |
          if git rev-parse "${{ steps.get_version.outputs.version }}" >/dev/null 2>&1; then
            echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Git tag
        if: steps.tag_check.outputs.tag_exists == 'false'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "${{ steps.get_version.outputs.version }}" -m "Release v${{ steps.get_version.outputs.version }}"
          git push origin "${{ steps.get_version.outputs.version }}"

      - name: Install dependencies and PyInstaller
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build Linux binary with PyInstaller
        run: |
          pyinstaller awv.spec
          mkdir awv-linux
          cp dist/awv awv-linux/awv
          cp AUTHOR.rst LICENSE awv-linux/
          tar -czvf awv-linux.tar.gz -C awv-linux .

      - name: Create .deb package
        run: |
          mkdir -p awv-deb/usr/local/bin
          mkdir -p awv-deb/DEBIAN
          cp dist/awv awv-deb/usr/local/bin/awv

          VERSION="${{ steps.get_version.outputs.version }}"
          echo "Package: auto-website-visitor" > awv-deb/DEBIAN/control
          echo "Version: $VERSION" >> awv-deb/DEBIAN/control
          echo "Section: utils" >> awv-deb/DEBIAN/control
          echo "Priority: optional" >> awv-deb/DEBIAN/control
          echo "Architecture: amd64" >> awv-deb/DEBIAN/control
          echo "Depends: python3" >> awv-deb/DEBIAN/control
          echo "Maintainer: nayandas69" >> awv-deb/DEBIAN/control
          echo "Description: Auto Website Visitor - automate browser visits to websites." >> awv-deb/DEBIAN/control

          dpkg-deb --build awv-deb
          mv awv-deb.deb awv-linux/auto-website-visitor_${VERSION}_amd64.deb

      - name: Upload Linux release asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ steps.get_version.outputs.version }}"
          name: "Release v${{ steps.get_version.outputs.version }}"
          body: |
            New features and improvements are included in this version. Download assets below.
            [CHANGELOG](CHANGELOG.md)
          files: |
            awv-linux.tar.gz
            awv-linux/auto-website-visitor_${{ steps.get_version.outputs.version }}_amd64.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows-build:
    runs-on: windows-latest
    needs: linux-build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies and PyInstaller
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build Windows EXE using PyInstaller spec
        run: pyinstaller awv.spec

      - name: Upload Windows release asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ needs.linux-build.outputs.version }}"
          files: dist/awv.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
