name: Release Tags

on:
  workflow_dispatch:
  push:
    paths:
      - 'awv.py'
    branches:
      - main

permissions:
  contents: write

jobs:
  linux-build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Extract version from setup.py
        id: get_version
        run: |
          VERSION=$(python setup.py --version)
          echo "Project version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if Git tag exists
        id: tag_check
        run: |
          if git rev-parse "${{ steps.get_version.outputs.version }}" >/dev/null 2>&1; then
            echo "Tag already exists. Skipping."
            echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Git tag
        if: steps.tag_check.outputs.tag_exists == 'false'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -a "${{ steps.get_version.outputs.version }}" -m "Release v${{ steps.get_version.outputs.version }}"
          git push origin "${{ steps.get_version.outputs.version }}"

      - name: Install dependencies and PyInstaller
        run: pip install --upgrade pip && pip install -r requirements.txt pyinstaller

      - name: Build Linux binary with PyInstaller spec
        run: |
          pyinstaller awv.spec
          mkdir awv-linux
          cp dist/downloader awv-linux/awv
          cp AUTHOR.rst LICENSE awv-linux/
          tar -czvf awv-linux.tar.gz -C awv-linux .

      - name: Upload Linux release asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ steps.get_version.outputs.version }}"
          name: "Release v${{ steps.get_version.outputs.version }}"
          body: |
          We changed some things in the code, so we decided to release a new version.
          Please check the [CHANGELOG](CHANGELOG.md) for more details.
          files: awv-linux.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows-build:
    runs-on: windows-latest
    needs: linux-build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies and PyInstaller
        run: pip install --upgrade pip && pip install -r requirements.txt pyinstaller

      - name: Build Windows EXE using PyInstaller spec
        run: pyinstaller awv.spec

      - name: Rename Windows executable
        run: Rename-Item -Path "dist/awv.exe" -NewName "Auto Website Visitor.exe"

      - name: Upload Windows release asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ needs.linux-build.outputs.version }}"
          files: dist/Auto Website Visitor.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
